export const apikey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dHhscmpmaHF6bnB3cmpseGNrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxMDc1MTY3MiwiZXhwIjoyMDI2MzI3NjcyfQ.qe9qX-N-zoCpiP6GjdwiihOgFt57g6lC6xPokKfohiQ";
export const endpoint = "https://qutxlrjfhqznpwrjlxck.supabase.co/rest/v1/recipe";
